#!/bin/bash

# This script will install the teamserver and dependencies on Ubuntu 16.04
# It expects the repo to be cloned into /opt/arsenal

# Install systemd service file
cp -f /opt/arsenal/contrib/arsenal.service /lib/systemd/system/arsenal.service

# Install python 3.6
add-apt-repository -y ppa:deadsnakes/ppa
apt-get update -y
apt-get install -y python3.6 uwsgi

# Create and activate a virtualenv
cd /opt/arsenal
python3.6 -m venv venv
source venv/bin/activate

# Install dependencies
pip install -r teamserver/teamserver/requirements/prod.txt

# Reload systemd daemons
systemctl daemon-reload
systemctl enable arsenal.service
